spring:
    config:
        import:
        - classpath:application-local.yaml
    profiles:
        active: local
    messages:
        basename: i18n/messages
        encoding: UTF-8

swagger:
    api:
        base-package: com.stdtrinfra.kubevmmanager.presentation
        path: /api/v1/**